package com.lewiswalker.savings.account;

import java.util.Optional;
import java.util.UUID;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.resilience.annotation.Retryable;
import org.springframework.stereotype.Component;

/**
 * Allocates account numbers from a Postgres sequence, in this process.
 *
 * <p>The demo adapter for {@link AccountNumberAllocator}. The brief asks for numbers
 * autogenerated by the API, so this is what ships; see the port for what this call
 * looks like against a real core banking platform.
 *
 * <p>Note what makes the retry policy below safe, because it is not safe in general.
 * Retrying an allocation is exactly the operation that can double-apply: a timed-out
 * call to a core banking platform may well have allocated a number, and trying again
 * would open a second account. It is only sound because {@code clientReference} lets
 * the far side recognise the replay and return the original allocation. Retry and
 * idempotency are not two features here; the first is unsafe without the second.
 */
@Component
public class LocalSequenceAccountNumberAllocator implements AccountNumberAllocator {

    private static final Logger log =
            LoggerFactory.getLogger(LocalSequenceAccountNumberAllocator.class);

    /** A residue of 10 is not a digit, so about one sequence value in eleven is wasted. */
    private static final int MAX_DRAWS = 32;

    private final AccountRepository repository;
    private final NzAccountNumberFormat format;

    public LocalSequenceAccountNumberAllocator(AccountRepository repository,
                                               NzAccountNumberFormat format) {
        this.repository = repository;
        this.format = format;
    }

    /**
     * {@inheritDoc}
     *
     * <p>{@code clientReference} is ignored here, and deliberately so rather than by
     * omission. It exists to make a retried allocation return the original number
     * instead of a second one — a problem that only arises when allocation crosses a
     * process boundary and its response can be lost. A local sequence draw is inside
     * the caller's transaction: if the transaction rolls back the number is simply
     * never used, and there is no partial state to reconcile. The parameter stays on
     * the port because the core adapter cannot do without it.
     */
    /*
     * Cannot fire against this adapter, and is annotated anyway because this is the seam
     * the real one drops into - the same reasoning as DemoCustomerDirectory. Exhausting
     * MAX_DRAWS locally is not merely improbable but impossible: the check digit's
     * position carries weight 1, so consecutive sequence values step the residue by a
     * fixed amount and cannot produce 10 thirty-two times running.
     */
    @Retryable(
            includes = AccountNumberAllocationException.class,
            maxRetries = 2,
            delay = 100,
            jitter = 50,
            multiplier = 2.0,
            maxDelay = 500,
            timeout = 2000)
    @Override
    public String allocate(UUID customerId, String clientReference) {
        for (int draw = 0; draw < MAX_DRAWS; draw++) {
            Optional<String> issued;
            try {
                issued = format.format(repository.nextAccountNumberSeed());
            } catch (IllegalStateException exhausted) {
                // The branch's number range is used up. Not a transient failure and not
                // something the caller did: it needs a new range registered with Payments
                // NZ and configured here, which is an operational event rather than a
                // request-handling one. Wrapped so it surfaces as a 503 rather than an
                // unhandled 500, and logged at error because somebody has to act on it.
                log.error("account number range exhausted; a new branch range is required",
                        exhausted);
                throw new AccountNumberAllocationException(
                        "the account number range is exhausted", exhausted);
            }
            if (issued.isPresent()) {
                return issued.get();
            }
        }
        throw new AccountNumberAllocationException(
                "no issuable account number after " + MAX_DRAWS + " sequence draws");
    }
}
