package com.lewiswalker.savings.account;

import java.util.Optional;
import java.util.UUID;
import org.springframework.resilience.annotation.Retryable;
import org.springframework.stereotype.Component;

/**
 * Allocates account numbers from a Postgres sequence, in this process.
 *
 * <p>The demo adapter for {@link AccountNumberAllocator}. The brief asks for numbers
 * autogenerated by the API, so this is what ships; see the port for what this call
 * looks like against a real core banking platform.
 *
 * <p>Note what makes the retry policy below safe, because it is not safe in general.
 * Retrying an allocation is exactly the operation that can double-apply: a timed-out
 * call to a core banking platform may well have allocated a number, and trying again
 * would open a second account. It is only sound because {@code clientReference} lets
 * the far side recognise the replay and return the original allocation. Retry and
 * idempotency are not two features here; the first is unsafe without the second.
 */
@Component
public class LocalSequenceAccountNumberAllocator implements AccountNumberAllocator {

    /** A residue of 10 is not a digit, so about one sequence value in eleven is wasted. */
    private static final int MAX_DRAWS = 32;

    private final AccountRepository repository;
    private final NzAccountNumberFormat format;

    public LocalSequenceAccountNumberAllocator(AccountRepository repository,
                                               NzAccountNumberFormat format) {
        this.repository = repository;
        this.format = format;
    }

    /**
     * {@inheritDoc}
     *
     * <p>{@code clientReference} is ignored here, and deliberately so rather than by
     * omission. It exists to make a retried allocation return the original number
     * instead of a second one — a problem that only arises when allocation crosses a
     * process boundary and its response can be lost. A local sequence draw is inside
     * the caller's transaction: if the transaction rolls back the number is simply
     * never used, and there is no partial state to reconcile. The parameter stays on
     * the port because the core adapter cannot do without it.
     */
    @Retryable(
            includes = AccountNumberAllocationException.class,
            maxRetries = 2,
            delay = 100,
            jitter = 50,
            multiplier = 2.0,
            maxDelay = 500,
            timeout = 2000)
    @Override
    public String allocate(UUID customerId, String clientReference) {
        for (int draw = 0; draw < MAX_DRAWS; draw++) {
            Optional<String> issued = format.format(repository.nextAccountNumberSeed());
            if (issued.isPresent()) {
                return issued.get();
            }
        }
        throw new AccountNumberAllocationException(
                "no issuable account number after " + MAX_DRAWS + " sequence draws");
    }
}
