package com.lewiswalker.savings.account.numbering;

import com.lewiswalker.savings.account.AccountRepository;
import java.util.Optional;
import java.util.UUID;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.resilience.annotation.Retryable;
import org.springframework.stereotype.Component;

/**
 * Stand-in for {@link AccountNumberAllocator}, drawing from a Postgres sequence in this
 * process. The brief asks for numbers autogenerated by the API, so this is what ships.
 */
@Component
public class LocalSequenceAccountNumberAllocator implements AccountNumberAllocator {

    private static final Logger log =
            LoggerFactory.getLogger(LocalSequenceAccountNumberAllocator.class);

    /** A residue of 10 is not a digit, so roughly one sequence value in eleven is skipped. */
    private static final int MAX_DRAWS = 32;

    private final AccountRepository repository;
    private final NzAccountNumberFormat format;

    public LocalSequenceAccountNumberAllocator(AccountRepository repository,
                                               NzAccountNumberFormat format) {
        this.repository = repository;
        this.format = format;
    }

    /** {@code clientReference} is ignored: a local draw leaves no partial state. */
    @Retryable(
            includes = AccountNumberAllocationException.class,
            maxRetries = 2,
            delay = 100,
            jitter = 50,
            multiplier = 2.0,
            maxDelay = 500,
            timeout = 2000)
    @Override
    public String allocate(UUID customerId, String clientReference) {
        for (int draw = 0; draw < MAX_DRAWS; draw++) {
            Optional<String> issued;
            try {
                issued = format.format(repository.nextAccountNumberSeed());
            } catch (IllegalStateException exhausted) {
                // The branch range is used up. Operational: it needs a new registered
                // range, so it is logged for someone to act on rather than passed to the
                // caller as something they did.
                log.error("account number range exhausted; a new branch range is required",
                        exhausted);
                throw new AccountNumberAllocationException(
                        "the account number range is exhausted", exhausted);
            }
            if (issued.isPresent()) {
                return issued.get();
            }
        }
        throw new AccountNumberAllocationException(
                "no issuable account number after " + MAX_DRAWS + " sequence draws");
    }
}
